name: CI

on:
  push:
    branches:
    - master
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 15

      - name: Cache Local Maven Repo
        uses: actions/cache@v2.1.2
        with:
          path: ~/.m2/repository
          key: maven-repo

      - uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: |
            [{"id": "highmed-dsf", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"},
             {"id": "de.numcodex", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]

      - name: Build
        run: mvn -B package

  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker image for aktin-broker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/aktin-broker/Dockerfile
        tags: |
          ghcr.io/${{ steps.prep.outputs.repository }}:${{ github.ref }}
          ghcr.io/${{ steps.prep.outputs.repository }}:latest
        push: false
